### PR TITLE
Items completion

### PR DESCRIPTION
**Pull request by advantagevarnson**
@droberts84 having issues making the completed tick box appear? i thought i was doing everything correctly

### CODE REVIEW

**Comment by advantagevarnson** [comment]
ive just added a new commit where i have modded the "checkbox" partial however still no joy.... @droberts84

**Comment by droberts84** [comment]
Can you give me more information?

- Where do you want the checkbox to appear?  What controller/action are you accessing?
- What view did you add the code to?
- What was the code you used?
- What are you seeing instead?  Are there any error message?

**Comment by advantagevarnson** [comment]
- i wanted the box to appear at the end of the listed item
- i added it to the users show as a partial that has been called

i used the partial given to us and it errored so i modded it slightly to make it work.

```
<%= link_to '', [@user, item], method: :delete, class: 'glyphicon glyphicon-ok' %>
```

its not showing up and theres no error :\

**Comment by droberts84** [comment]
Ok, so you're expecting bootstrap to find an element with those classes and display an appropriate glyphicon. First, let's examine the HTML with chrome dev tools

It generated this, which looks right.
`<a class="glyphicon glyphicon-ok" rel="nofollow" data-method="delete" href="/users/1/items/2"></a>`

You can see more documentation on [glyphicons here](http://getbootstrap.com/components/#glyphicons)

So, my next thought is bootstrap may not be set up properly, particularly since no other elements on you page are being styled.

Take a look down that route and let me know what you find.

**Pull request closed without merging**
