### PR TITLE
Items completion

### PR DESCRIPTION
**Pull request by advantagevarnson**
ive updated this to work with ajax however it doesnt seem to dynamically remove the checkboxes
@droberts84 even though when i refresh the page the items are complete?

### CODE REVIEW

**Comment by advantagevarnson** [comment]
This is the servers response... @droberts84 

```
Started DELETE "/users/1/items/40" for ::1 at 2016-02-14 13:22:38 +0800
Processing by ItemsController#destroy as JS
  Parameters: {"user_id"=>"1", "id"=>"40"}
  User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT 1  [["id", 1]]
  Item Load (0.2ms)  SELECT  "items".* FROM "items" WHERE "items"."id" = ? LIMIT 1  [["id", 40]]
   (0.2ms)  begin transaction
  SQL (0.5ms)  DELETE FROM "items" WHERE "items"."id" = ?  [["id", 40]]
   (37.5ms)  commit transaction
  Rendered items/destroy.js.erb (0.5ms)
Completed 200 OK in 65ms (Views: 21.8ms | ActiveRecord: 38.5ms)
```

**Comment by droberts84** [comment]
The log you copied is from the server.

Since you said that everything looks good once you refresh, that is a
strong indication that the Ruby / server side code is working properly, but
the javascript / clientside code is not updating the page in the way you
expect.

Are there any error messages in the JS console in Chrome dev tools? Have
you tried entering the JS returned by items/destroy.js.erb in the JS
console to see if it works?

**Comment by advantagevarnson** [comment]
this has been completed on a new commit... does that mean i have to reopen a new pull request @droberts84 ?

**Comment by advantagevarnson** [comment]
and can i please merge this as its completed so i can move forth?

**Comment by advantagevarnson** [comment]
also quickly... i seem to remember you quickly mentioned the other day that i should merge to master on github not locally and then pull down the master branch... or can i still merge locally then push to github?

**Comment by droberts84** [comment]
> this has been completed on a new commit... does that mean i have to reopen a new pull request

Nope, any commits on the same branch will automatically be added to the PR when you push to GitHub.

> and can i please merge this as its completed so i can move forth?

Definitely.. I don't want to hold you from proceeding


 > also quickly... i seem to remember you quickly mentioned the other day that i should merge to master on github not locally and then pull down the master branch... or can i still merge locally then push to github?

I would recommend merging the PR on GitHub and pulling down locally.  If you merge locally you're shortcutting the PR process.

**Comment by droberts84** [comment]
The complete looks great, but it seems this broke the ability to create new tasks

I get the following error when trying to create a task: 
`Missing template items/create, application/create`

Also, good job adding bootstrap, but it goes off the screen in my browser.  See https://www.evernote.com/l/AFW_HJ6OmepHsZ8h_4RB8UgMkNAioWoipAoB/image.png

Checkout the [Bootstrap grid system](http://getbootstrap.com/css/#grid).  Row tags need to be nested in a `.container` or `.container-fluid`.  I often like to put this in the application layout file so that it wraps every page.

**Comment by advantagevarnson** [comment]
as far as i can tell the code is trying to find create.html.erb not create.js.erb.....

ive tried referring to create.js,erb, rendering create.js.erb

i cant figure it out which is frustrating because i can tell whats wrong :\

**Comment by droberts84** [comment]
Ok, great.  If that's the case this is an easy fix.  Rails will, by default, look for a view matching the requested content type of the request.  So if you create is requested from a standard POST action, it defaults to responding in HTML and using an HTML view.  See more [in this rails guide](http://guides.rubyonrails.org/layouts_and_rendering.html#using-render).  It sounds like you want to make this requested with AJAX and have the server respond with JS, instead of a standard HTML request.  To do that, you need to specify `remote: true` in the [form_for helper](https://github.com/advantagevarnson/Blocitoff/blob/master/app/views/items/_form.html.erb#L1) which creates a form to submit via ajax. See the [rails javascript guide](http://guides.rubyonrails.org/working_with_javascript_in_rails.html#form-for) for more info.

**Pull request merged**
